# Copyright © 2025 GUIHO Technologies as represented by Cristóvão GUIHO
# All Rights Reserved.

steps:
  - name: gcr.io/cloud-builders/docker
    entrypoint: 'bash'
    args:
      - -c
      - docker build --no-cache --tag $_GAR_IMAGE_PATH:$_TAG_VERSION ./core --file ./core/Dockerfile --network=cloudbuild
    id: Build

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GAR_IMAGE_PATH:$_TAG_VERSION'
    id: Push

images:
  - '$_GAR_IMAGE_PATH:$_TAG_VERSION'

options:
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: ALLOW_LOOSE
  dynamicSubstitutions: true
  automapSubstitutions: true

substitutions:
  _TAG_VERSION: ${TAG_NAME#*@}
  _GAR_IMAGE_PATH: europe-west4-docker.pkg.dev/guiho40/guiho/nante40-core

tags:
  - g1000
  - guiho
  - nante40-core
