#!/bin/bash


secrets_array=(
  "RESEND_API_KEY_SEND_ACCESS=RESEND_API_KEY_SEND_ACCESS:latest"

  "SESSION_ENCRYPTION_KEY=G0001_SESSION_ENCRYPTION_KEY:latest"
  "SESSION_SIGNING_KEY=G0001_SESSION_SIGNING_KEY:latest"

  "SESSION_PAST_ENCRYPTION_KEY_0=G0001_SESSION_PAST_ENCRYPTION_KEY_0:latest"
  "SESSION_PAST_ENCRYPTION_KEY_1=G0001_SESSION_PAST_ENCRYPTION_KEY_1:latest"
  "SESSION_PAST_ENCRYPTION_KEY_2=G0001_SESSION_PAST_ENCRYPTION_KEY_2:latest"
  "SESSION_PAST_ENCRYPTION_KEY_3=G0001_SESSION_PAST_ENCRYPTION_KEY_3:latest"

  "SESSION_PAST_SIGNING_KEY_0=G0001_SESSION_PAST_SIGNING_KEY_0:latest"
  "SESSION_PAST_SIGNING_KEY_1=G0001_SESSION_PAST_SIGNING_KEY_1:latest"
  "SESSION_PAST_SIGNING_KEY_2=G0001_SESSION_PAST_SIGNING_KEY_2:latest"
  "SESSION_PAST_SIGNING_KEY_3=G0001_SESSION_PAST_SIGNING_KEY_3:latest"

  "PG_HOST=G0000_GUIHO_PG_HOST:latest"
  "PG_PASSWORD=G0000_GUIHO_PG_PASSWORD:latest"

  "VALKEY_HOST=G0000_GUIHO_PG_HOST:latest" # Valkey and Postgres use the same host 
  "VALKEY_PASSWORD=G0000_GUIHO_VALKEY_PASSWORD:latest"
)

join_by_comma() {
  local IFS=","
  echo "$*"
}

one_string=$(join_by_comma "${secrets_array[@]}")

echo "$one_string"



